project_id = "kxlkwyfbtjqsthybfgex"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.upload-vendas]
verify_jwt = false

[functions.gerar-previsao] 
verify_jwt = false

[functions.dashboard-dados]
verify_jwt = false